site_name: HuuTho's Blog

theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'light blue'

nav:
  - Home: index.md
  - Home1: index1.md
  - Block chain: blockchain/lecture.md
  - About: about.md
  - Graph View: graph.md

  - MKDocs Material: mkdocs_material/index.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
